version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  target-branch: develop
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/docker"
  schedule:
      interval: daily
  target-branch: develop
  labels:
  - docker_dependencies
